import { describe, expect, it } from "vitest";
import { MAX_CAPTURE_BYTES, ValidationError, parseCreateRecord } from "../src/record";

const valid = {
  id: "01983f0d-7b32-7b4d-8d5b-8ff24c3b1001",
  recordedAt: "2026-07-25T09:00:00.000+09:00",
  data: { kind: "capture", content: "Capture API 설계를 시작한다.", source: { client: "desktop", deviceId: "macbook-main" } },
};

describe("parseCreateRecord", () => {
  it("keeps a small capture and removes empty optional fields", () => {
    const result = parseCreateRecord({ ...valid, data: { ...valid.data, source: { ...valid.data.source, clientVersion: "" }, context: { browser: { url: "https://example.com", title: "" } } } });
    expect(result.data).toEqual({ kind: "capture", content: valid.data.content, source: valid.data.source, context: { browser: { url: "https://example.com" } } });
  });
  it("rejects large content and forbidden attachment-like fields", () => {
    expect(() => parseCreateRecord({ ...valid, data: { ...valid.data, content: "a".repeat(MAX_CAPTURE_BYTES + 1) } })).toThrow(ValidationError);
    expect(() => parseCreateRecord({ ...valid, data: { ...valid.data, attachment: "data:image/png;base64,abc" } })).toThrow("not allowed");
  });
  it("requires an id generated by the client", () => {
    expect(() => parseCreateRecord({ ...valid, id: "not-a-uuid" })).toThrow("must be a UUID");
  });
  it("normalizes recordedAt to UTC for stable ordering", () => {
    const result = parseCreateRecord({ ...valid, recordedAt: "2026-07-25T09:00:00.000+09:00" });
    expect(result.recordedAt).toBe("2026-07-25T00:00:00.000Z");
  });
});
